# Toutes les donnée pour la configuration pour le jeu

# Les paramètres pour l'écran
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
FPS = 120

# Les différents chemins des images et son qui se situent dans le dossier assets
ASSETS_DIR = "assets"
BACKGROUND_PATH = f"{ASSETS_DIR}/Background.png"
BANNER_PATH = f"{ASSETS_DIR}/banner.png"
BUTTON_PATH = f"{ASSETS_DIR}/button.png"
CREDITS_IMG_PATH = f"{ASSETS_DIR}/credits.png"
QUIT_IMG_PATH = f"{ASSETS_DIR}/quit.png"
SETTINGS_IMG_PATH = f"{ASSETS_DIR}/settings.png"
GAME_OVER_IMG_PATH = f"{ASSETS_DIR}/Game_over.png"
PLAYER_IMG_PATH = f"{ASSETS_DIR}/Mage.png"
OGRE_IMG_PATH = f"{ASSETS_DIR}/ogre.png"
DRAGON_IMG_PATH = f"{ASSETS_DIR}/dragon.png"
PROJECTILE_IMG_PATH = f"{ASSETS_DIR}/projectile.png"
COMET_IMG_PATH = f"{ASSETS_DIR}/comet.png"
FONT_PATH = f"{ASSETS_DIR}/CustomFont.ttf"
SOUNDS_DIR = f"{ASSETS_DIR}/sounds"
MUSIC_MENU_PATH = f"{SOUNDS_DIR}/musique_ecran_d'acceuil.ogg"
MUSIC_GAME_PATH = f"{SOUNDS_DIR}/musique_dans_le_jeux.ogg"
SOUND_CLICK_PATH = f"{SOUNDS_DIR}/click.ogg"
SOUND_GAME_OVER_PATH = f"{SOUNDS_DIR}/game_over.ogg"
SOUND_METEORITE_PATH = f"{SOUNDS_DIR}/meteorite.ogg"
SOUND_TIR_PATH = f"{SOUNDS_DIR}/tir.ogg"

# Les différentes couleurs utilisées
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
GRAY = (94, 90, 90)
DARK_GRAY = (50, 50, 50)
LIGHT_GRAY = (180, 180, 180)
GREEN = (0, 255, 0)

# Les tailles et les positions des hud
BANNER_SCALE_FACTOR = 0.42
BANNER_HEIGHT_FACTOR = 0.7
BANNER_Y_FACTOR = 0.05
BUTTON_SCALE_FACTOR = 0.25
BUTTON_HEIGHT_FACTOR = 0.14
BUTTON_Y_FACTOR = 1.6
CREDITS_SCALE_FACTOR = 0.15
CREDITS_HEIGHT_FACTOR = 0.09
SETTINGS_SCALE_FACTOR = 0.15
SETTINGS_HEIGHT_FACTOR = 0.09
QUIT_SCALE_FACTOR = 0.25
QUIT_HEIGHT_FACTOR = 0.14
GAME_OVER_SCALE = (SCREEN_WIDTH, SCREEN_HEIGHT)
POPUP_WIDTH_FACTOR = 0.3
POPUP_HEIGHT_FACTOR = 0.28
CLOSE_BTN_RADIUS = 18

# La tailles des polices
TITLE_FONT_SIZE = 45
TEXT_FONT_SIZE = 30
CREDIT_FONT_SIZE = 25
PAUSE_FONT_SIZE = 50
SMALL_FONT_SIZE = 36
RESTART_FONT_SIZE = 40

# Toutes les paramètre du jeu
INITIAL_MUSIC_VOLUME = 0.5
INITIAL_SOUND_VOLUME = 0.5
PLAYER_MAX_HEALTH = 100
PLAYER_ATTACK = 25
PLAYER_VELOCITY = 3
MONSTER_ATTACK_OGRE = 0.3
MONSTER_ATTACK_DRAGON = 0.8
DRAGON_HEALTH = 250
DRAGON_LOOT = 50
OGRE_LOOT = 10
PROJECTILE_VELOCITY = 10
COMET_VELOCITY_MIN = 4
COMET_VELOCITY_MAX = 6
COMET_DAMAGE = 20
COMET_EVENT_SPEED = 20

# dimmension des boutons de fin de partie
RESTART_RECT = (0.21, 0.25, 0.18, 0.055)
MENU_RECT = (0.21, 0.32, 0.18, 0.055)

# Menu paramètres
SETTINGS_WINDOW_WIDTH = 400
SETTINGS_WINDOW_HEIGHT = 320
MUSIC_BAR_MARGIN_X = 50
MUSIC_BAR_Y = 90
SOUND_BAR_Y = 160